### PR TITLE
Added timeout, fixed request bug, better error handling, fetched other pull requests

### PR DESCRIPTION
**Pull request by seydx**
**Fetched Pull Request https://github.com/hendrikw01/tr-064/pull/13 from @NicolaiSchmid**
- The XML Implementation for setting TR-064 Action was not correctly implemented. 
- Fixed XML Building and created a new Function Syntax.
- Altered Readme accordingly.
- Added Example for toggling WLAN of a FritzBox

**Additional functions & Bugfixes:**
- New timeout function
- Fixed bug with request > 3 (authorization error)
- Better error handling

### CODE REVIEW

**Comment by NicolaiSchmid** [comment]
I think this package is not maintained anymore. But if you want, we could fork it and publish our own version.

**Comment by seydx** [comment]
Hey that sounds good

**Comment by NicolaiSchmid** [comment]
Okay, then I'm gonna set up a new repo, with auto deploy and invite you as a maintainer.

**Comment by Apollon77** [comment]
Can you please post the new repo and package then here please?

**Comment by NicolaiSchmid** [comment]
How times change, now I haven't used this module in three years.
But, the last working version can be found here:
https://github.com/NicolaiSchmid/tr064
Feel free to improve, make PRs or fork

**Pull request closed without merging**
